version: '3.9'

services:

  app-lucenia:
    container_name: stac-fastapi-lucenia
    image: stac-utils/stac-fastapi-lucenia
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev.os
    environment:
      - STAC_FASTAPI_TITLE=stac-fastapi-lucenia
      - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with a Lucenia backend
      - STAC_FASTAPI_VERSION=3.0.0a2
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_HOST=host.docker.internal
      - ES_PORT=9200
      - ES_USE_SSL=true
      - ES_VERIFY_CERTS=false
      - BACKEND=opensearch
      - ES_USER=admin
      - ES_PASS=MyStrongPassword123!
    ports:
      - "8082:8082"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      # - ./osdata:/usr/share/opensearch/data
    command:
      bash -c "python -m stac_fastapi.opensearch.app"



