version: '3.9'

services:
  lucenia-node:
    image: lucenia/lucenia:0.2.1
    container_name: lucenia-node
    environment:
      - cluster.name=lucenia-cluster
      - node.name=lucenia-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "LUCENIA_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - LUCENIA_INITIAL_ADMIN_PASSWORD=MyStrongPassword123!
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Lucenia user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - lucenia-data:/usr/share/lucenia/data
      - ./node/config/lucenia.yml:/usr/share/lucenia/config/lucenia.yml
      - ./node/config/trial.crt:/usr/share/lucenia/config/trial.crt
    ports:
      - 9200:9200
    networks:
      - lucenia-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
volumes:
  lucenia-data:
networks:
  lucenia-net:



