version: '3'
services:
  search-node1: # This is also the hostname of the container within the Docker network (i.e. https://search-node1/)
    image: opensearchproject/opensearch:2.18.0 # Specifying the latest available image - modify if you want a specific version
    container_name: search-node1
    environment:
      - cluster.name=search-cluster # Name the cluster
      - node.name=search-node1 # Name the node that will run in this container
      - discovery.seed_hosts=search-node1,search-node2,search-node3 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=search-node1,search-node2,search-node3 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD} 
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files - set to at least 65536
        hard: 65536
    volumes:
      - search-data1:/usr/share/opensearch/data # Creates volume called search-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - search-net # All of the containers will join the same Docker bridge network
  search-node2:
    image: opensearchproject/opensearch:2.18.0
    container_name: search-node2
    environment:
      - cluster.name=search-cluster
      - node.name=search-node2
      - discovery.seed_hosts=search-node1,search-node2,search-node3
      - cluster.initial_cluster_manager_nodes=search-node1,search-node2,search-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-data2:/usr/share/opensearch/data
    networks:
      - search-net
  search-node3:
    image: opensearchproject/opensearch:2.18.0
    container_name: search-node3
    environment:
      - cluster.name=search-cluster
      - node.name=search-node3
      - discovery.seed_hosts=search-node1,search-node2,search-node3
      - cluster.initial_cluster_manager_nodes=search-node1,search-node2,search-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-data3:/usr/share/opensearch/data
    networks:
      - search-net

volumes:
  search-data1:
  search-data2:
  search-data3:

networks:
  search-net:
