[INPUT]
    Name tail
    Path /var/log/*.log
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
    Skip_Empty_Lines On
    Refresh_Interval 10
    Tag logs.raw

[FILTER]
    Name record_modifier
    Match logs.*
    Record environment demo
    Record team devops
    Record service fluent-bit-tutorial
    Record version 1.0.0

[OUTPUT]
    Name opensearch
    Match *
    Host lucenia-node
    Port 9200
    HTTP_User admin
    HTTP_Passwd MyStrongPassword123_
    tls On
    tls.verify Off
    Index docker-logs
    Generate_ID On
    Suppress_Type_Name On
    Retry_Limit 5
    Workers 1